In [1]:
import numpy as np

## Arrays

In [2]:
a = np.array([1, 2, 3])   
print(type(a))            
print(a.shape)            
print(a[0], a[1], a[2])   
a[0] = 5                  
print(a)                  


<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [7]:
b = np.array([[1,2,3],[4,5,6]])    
print(b.shape)                     
print(b)   

print(b[1,2])

(2, 3)
[[1 2 3]
 [4 5 6]]
6


## Matrizes comuns

In [13]:
import numpy as np

print('Zeros')
a = np.zeros((2,2))   
print(a)              
                      

print('Ones')
b = np.ones((3,2))    
print(b)              


print('Matriz Cheia')
c = np.full((2,2), 7) 
print(c)              
                      

print('Identidade')
d = np.eye(5)         
print(d)              
                      

print('Aleatório')
e = np.random.random((2,2))  
print(e)                     
                             

Zeros
[[0. 0.]
 [0. 0.]]
Ones
[[1. 1.]
 [1. 1.]
 [1. 1.]]
Matriz Cheia
[[7 7]
 [7 7]]
Identidade
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Aleatório
[[0.98531538 0.31517051]
 [0.21381885 0.88504207]]


## Slicing

In [14]:
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])


# [[2 3]
#  [6 7]]
b = a[:2, 1:3]


print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


In [17]:
#np.arrange
np.arange(4)

array([0, 1, 2, 3])

In [16]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a) 

# Array de índices
b = np.array([0, 2, 0, 1])

print(a[np.arange(4), b])  


a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


## Indexing lógico

In [21]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   
print(bool_idx)      
                     
                     

print(a[bool_idx]) 

# Equivalente
print(a[a > 2])     

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


## Tipos em vetores

In [22]:
x = np.array([1, 2])   
print(x.dtype)         

x = np.array([1.0, 2.0])  
print(x.dtype)             

x = np.array([1, 2], dtype=np.int64)   
print(x.dtype)                         

int64
float64
int64


## Operações entre vetores

In [28]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [29]:
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
#print(np.add(x, y))


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [30]:
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
#print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]


In [ ]:
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
#print(np.multiply(x, y))

In [31]:
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
#print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [32]:
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


## Multiplicação de Matrizes

In [25]:
v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


In [27]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

y.dot(x)

array([[23, 34],
       [31, 46]])

## Operações em vetores
[Documentação](https://docs.scipy.org/doc/numpy/reference/routines.math.html) 

In [40]:
x = np.array([[1,2],[3,4],[8,12]])
print(x)

[[ 1  2]
 [ 3  4]
 [ 8 12]]


In [41]:
print(np.sum(x))  
print(np.sum(x, axis=0))  
print(np.sum(x, axis=1))  

30
[12 18]
[ 3  7 20]


In [42]:
print(np.mean(x))  
print(np.mean(x, axis=0))  
print(np.mean(x, axis=1))  

5.0
[4. 6.]
[ 1.5  3.5 10. ]


## Redimensionamento
[documentação](https://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html)

In [43]:
x = np.array([[1,2], [3,4]])
print(x)    
print(x.T)  

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [44]:
v = np.array([1,2,3])
print(v)    
print(v.T)  

[1 2 3]
[1 2 3]


## Broadcasting
Permite realizar operações entre vetores de diferentes tamanhos

In [49]:
# Somar o vetro 'v' a cada linha da matriz 'x'
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.zeros(x.shape)  

for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 2.  2.  4.]
 [ 5.  5.  7.]
 [ 8.  8. 10.]
 [11. 11. 13.]]


In [50]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   
print(vv)                 #        "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  
print(y)  

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [51]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v 
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


## Aplicação: Movimento Geométrico Browniano (MGB)
𝑆𝑡=𝑆0*𝑒𝑥𝑝((𝜇−𝜎ˆ2/2)𝑡−𝜎𝑊𝑡)

In [69]:
import matplotlib.pyplot as plt
%matplotlib inline
T = 10
N = 100
dt = 0.01
mu = 0.01*dt
sigma = 0.1
S0 = 100
np.random.seed(1)

